<a href="https://colab.research.google.com/github/TamizharasanG/Guvi_Tasks/blob/main/copy_of_numpy_tasks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [ ]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [ ]:
np.__version__

'1.21.6'

#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [ ]:
x = np.array([i for i in range(1, 21)])
print(x)
print(x.size)
print(x.itemsize)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
20
8


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [ ]:
np.info()

 info(object=None, maxwidth=76,
      output=<ipykernel.iostream.OutStream object at 0x7f7142f23f10>,
      toplevel='numpy')

Get help information for a function, class, or module.

Parameters
----------
object : object or str, optional
    Input object or name to get information about. If `object` is a
    numpy object, its docstring is given. If it is a string, available
    modules are searched for matching objects.  If None, information
    about `info` itself is returned.
maxwidth : int, optional
    Printing width.
output : file like object, optional
    File like object that the output is written to, default is
    ``stdout``.  The object has to be opened in 'w' or 'a' mode.
toplevel : str, optional
    Start search at this level.

See Also
--------
source, lookfor

Notes
-----
When used interactively with an object, ``np.info(obj)`` is equivalent
to ``help(obj)`` on the Python prompt or ``obj?`` on the IPython
prompt.

Examples
--------
>>> np.info(np.polyval) # doctest: +SKIP

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [ ]:
x = np.arange(10, 49)
x


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [ ]:
x[::-1]


array([48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [ ]:
x = np.arange(0, 9).reshape(3, 3)
print(x.shape)
x

(3, 3)


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [ ]:
x = np.array([1, 2, 0, 0, 4, 0])
np.nonzero(x)

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [ ]:
x = np.eye(3, 3)
x

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [ ]:
x = np.random.random(27).reshape(3, 3, 3)
x

array([[[0.91742193, 0.60199542, 0.8370491 ],
        [0.97108528, 0.95894722, 0.90816176],
        [0.44578049, 0.4029511 , 0.61181692]],

       [[0.20893872, 0.13150176, 0.05833979],
        [0.35763366, 0.67885351, 0.93516546],
        [0.69942959, 0.82071106, 0.13860876]],

       [[0.84224422, 0.11250213, 0.73097851],
        [0.16446555, 0.63180456, 0.42678248],
        [0.49765617, 0.85359357, 0.28993104]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [ ]:
x = np.random.random(100).reshape(10, 10)
print(x)
print("Minimum : ",np.min(x))
print("Maximum : ",np.max(x))

[[0.05772798 0.21156714 0.08648786 0.59139727 0.79997331 0.09699441
  0.97666584 0.65475968 0.76244355 0.46290827]
 [0.73161832 0.61819495 0.88191878 0.31324079 0.11396279 0.22414087
  0.59259454 0.45899751 0.37484118 0.15290365]
 [0.380342   0.7423078  0.06289981 0.99356703 0.52241338 0.29631009
  0.91486961 0.96755578 0.16393745 0.24348603]
 [0.5655824  0.19939969 0.2407527  0.7516825  0.47315238 0.13129377
  0.2864911  0.35236081 0.68365105 0.95936237]
 [0.28890161 0.19201701 0.61550873 0.27950082 0.91866969 0.59954091
  0.86101154 0.59459477 0.66243021 0.12276753]
 [0.42698602 0.1484311  0.30001224 0.25085878 0.30680371 0.20138227
  0.1840198  0.3161006  0.56005275 0.45116297]
 [0.70524651 0.10651585 0.13796545 0.34581121 0.41142166 0.85157069
  0.58917418 0.8346211  0.19847879 0.8630312 ]
 [0.0204735  0.57318398 0.77397728 0.15914103 0.50640191 0.93668327
  0.58056953 0.69143408 0.47708824 0.94318652]
 [0.09928528 0.16878706 0.43695626 0.53277112 0.95221099 0.84993491
  0.48688141

#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [ ]:
x = np.random.random(30)
print("Mean : ", np.mean(x))
x

Mean :  0.5005181471409196


array([2.52636239e-01, 2.66988188e-01, 4.73747482e-01, 9.67348289e-01,
       1.06791968e-01, 1.43883004e-01, 2.98309485e-01, 2.42767309e-01,
       3.14394376e-03, 1.46077683e-01, 7.98051823e-01, 7.25280051e-01,
       3.26261421e-01, 9.81661136e-01, 8.70769656e-01, 7.13028468e-01,
       2.15870989e-04, 7.46338735e-01, 1.98802798e-01, 2.85325318e-01,
       9.72867326e-01, 7.92960692e-01, 3.01599044e-01, 9.57971524e-01,
       9.71820766e-01, 8.53074799e-01, 6.70709221e-02, 6.20781282e-01,
       3.89893330e-01, 5.40075859e-01])

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [ ]:
x = np.ones((5, 5))
print(x)
x[1:-1, 1:-1] = 0
x

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [ ]:
x = np.ones((3, 3))
np.pad(x, (1,))

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [ ]:
False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [ ]:
x = np.diag([0, 1, 2, 3, 4])
print(x.shape)
x

(5, 5)


array([[0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [ ]:
x = np.ones((3,3))
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)
x.shape

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


(8, 8)

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [ ]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [ ]:
x = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [ ]:
x = np.random.random((5,5))
print(x)
x_max, x_min = x.max(), x.min()
x = (x - x_min)/(x_max - x_min)
print("*****************************")
print(x)

[[0.28348729 0.72913627 0.28143974 0.71352719 0.85385901]
 [0.20132559 0.26129668 0.75020338 0.70598415 0.0814054 ]
 [0.07229865 0.5942971  0.00506508 0.41426999 0.69049926]
 [0.21982904 0.58543899 0.12494483 0.50315003 0.21831492]
 [0.17472184 0.62810769 0.50151011 0.11008668 0.57165308]]
*****************************
[[0.32802097 0.85305887 0.32560867 0.83466916 1.        ]
 [0.2312228  0.30187727 0.87787893 0.82578238 0.08993975]
 [0.07921071 0.69419914 0.         0.4821016  0.80753897]
 [0.2530225  0.68376303 0.1412354  0.58681494 0.25123865]
 [0.19987979 0.73403283 0.58488287 0.12373039 0.66752127]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [ ]:
color = np.dtype([("r", np.ubyte, 1), ("g", np.ubyte, 1), ("b", np.ubyte, 1), ("a", np.ubyte, 1)])

<ipython-input-67-02daf17723c8>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  color = np.dtype([("r", np.ubyte, 1), ("g", np.ubyte, 1), ("b", np.ubyte, 1), ("a", np.ubyte, 1)])


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [ ]:
x = np.dot(np.ones((5, 3)), np.ones((3, 2)))
x

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [ ]:
x = np.arange(21)
print(x)
x[(3 < x) & (x <= 8)] *= -1
x

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


array([ 0,  1,  2,  3, -4, -5, -6, -7, -8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
9

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
z = np.arange(1, 6)
z**z
2 << z >> 2
z <- z
z/1/1

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
0
0
np.array([np.nan]).astype(int).astype(float)

array([-9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [ ]:
x = np.random.uniform(-10,+10,10)
print(x)
print (np.trunc(x + np.copysign(0.5, x)))

[-7.7459549  -0.54732929  5.61622447  4.39527411  0.41283743 -3.33955504
 -7.93565145  0.11614747 -0.04943933  7.65120674]
[-8. -1.  6.  4.  0. -3. -8.  0. -0.  8.]


#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [ ]:
x = np.random.randint(0, 10, 10)
y = np.random.randint(0, 20, 10)
z = np.intersect1d(x, y)
print(x)
print(y)
print(z)

[2 1 0 7 8 8 7 9 1 8]
[ 0  3  8 13  9  6  4 18  4  0]
[0 8 9]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [ ]:
# Suicide mode on

defaults = np.seterr(all="ignore")
x = np.ones(1) / 0
# Removing the sucide mode
_ = np.seterr(**defaults)


with np.errstate(divide='ignore'):
  x = np.arange(5) / 0



#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [ ]:
Today = np.datetime64("today", "D")
Yesterday = np.datetime64("today", "D") - np.timedelta64(1, "D")
Tomorrow =  np.datetime64("today", "D") + np.timedelta64(1, "D")
print(Today,"\n",Tomorrow,"\n",Yesterday)

2023-01-10 
 2023-01-11 
 2023-01-09


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [ ]:
july_2016 = np.arange( "2016-07", "2016-08", dtype = "datetime64[D]")
july_2016

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [ ]:
x = np.ones(3)*1
print(x)
y = np.ones(3)*2
print(y)
z = np.ones(3)*3
print(z)
np.add(x, y,out=y)

np.divide(x,2,out=x)

np.negative(x,out=x)

a = np.multiply(x, y,out=x)

a

[1. 1. 1.]
[2. 2. 2.]
[3. 3. 3.]


array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [ ]:
x = np.random.uniform(0, 10, 10)
print(x)
print(x-x%1)
print(np.floor(x))
print(np.ceil(x) - 1)
print(np.trunc(x))
print(x.astype(int))

[7.30744162 4.21615573 5.62655622 3.26143558 9.83546653 0.25310418
 0.27112893 7.74775173 0.91049206 0.97500557]
[7. 4. 5. 3. 9. 0. 0. 7. 0. 0.]
[7. 4. 5. 3. 9. 0. 0. 7. 0. 0.]
[7. 4. 5. 3. 9. 0. 0. 7. 0. 0.]
[7. 4. 5. 3. 9. 0. 0. 7. 0. 0.]
[7 4 5 3 9 0 0 7 0 0]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [ ]:
x = np.zeros((5, 5))
x += np.arange(5)
x

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [ ]:
def generator():
  for i in range(10):
    yield i
x = np.fromiter(generator(), dtype = int, count = -1)
x

array([0, 1, 2, 3, 4])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [ ]:
x = np.linspace(0, 1, 12)[1 : -1]
x

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [ ]:
x = np.random.randint(0 , 100, 10)
np.sort(x)

array([ 0, 13, 18, 25, 31, 38, 78, 80, 87, 94])

#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [ ]:
x = np.arange(1, 11)
np.add.reduce(x)

55

#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [ ]:
x = np.random.randint(0, 10, 5)
y = np.random.randint(0, 10, 5)
a = np.allclose(x, y)
b = np.array_equal(x, y)
print(a)
print(b)
print(x)
print(y)

False
False
[0 0 0 2 8]
[5 6 5 8 0]


#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [ ]:
x = np.arange(11)
x.flags.writeable = False
try:
  x[0] = 2
except ValueError:
  print("This array is immutable")

This array is immutable


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [ ]:
x = np.random.random((10, 2))
a = x[:, 0]
b = x[:, 1]
c = np.sqrt(a**2, b**2)
d = np.arctan2(a, b)
print(c)
print(d)
print(x)

[0.40759001 0.60027201 0.69587484 0.21741631 0.26623112 0.63988973
 0.79729265 0.31771418 0.03648164 0.25980827]
[0.55378808 0.88355523 0.613044   0.43222689 0.60682856 0.96868489
 0.75054659 0.32447402 0.03890891 0.80381356]
[[0.40759001 0.65917943]
 [0.60027201 0.4926483 ]
 [0.69587484 0.98921806]
 [0.21741631 0.47129271]
 [0.26623112 0.38350303]
 [0.63988973 0.43975844]
 [0.79729265 0.85489739]
 [0.31771418 0.94455981]
 [0.03648164 0.93714343]
 [0.25980827 0.25041132]]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [ ]:
x = np.random.randint(0, 100, 10)
print(x)
x[x.argmax()] = 0
x

[19 28 64 48 68 29 79  7 58 34]


array([19, 28, 64, 48, 68, 29,  0,  7, 58, 34])

#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [ ]:
x = np.zeros((5,5), [('a',float),('b',float)])
x['a'], x['b'] = np.meshgrid(np.linspace(0,1,5),
np.linspace(0,1,5))
print(x)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [ ]:
x = np.arange(1, 9)
y = x+0.5
a = 1/np.subtract.outer(x, y)
a



#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [ ]:
for dtype in [np.int8, np.int32, np.int64]:
  print(np.iinfo(dtype).min)
  print(np.iinfo(dtype).max)

for dtype in [np.float32, np.float64]:
  print(np.finfo(dtype).min)
  print(np.finfo(dtype).max)
  print(np.finfo(dtype).eps)

#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [ ]:
np.set_printoptions()
x = np.zeros((2, 2))
x

array([[0., 0.],
       [0., 0.]])

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [ ]:
x = np.arange(50)
y = np.random.uniform(0, 100, 50)
a = (np.abs(x-y)).argmin()
print(x[a])


28


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [ ]:
x = np.zeros(10, [ ('position', [ ('x', float, 1),('y', float, 1)]),
('color', [ 
    ('r', float, 1),
    ('g', float, 1),
    ('b', float, 1)
    ])
])

print(x)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


<ipython-input-98-de5d63102e18>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  x = np.zeros(10, [ ('position', [ ('x', float, 1),('y', float, 1)]),


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [ ]:
a = np.random.random((10, 2))
x, y = np.atleast_2d(a[:, 0], a[:, 1])
b = np.sqrt((x-x.T)**2, (y - y.T)**2)
b

array([[0.        , 0.36308983, 0.05382267, 0.01471509, 0.38542725,
        0.22780465, 0.40625215, 0.51535236, 0.25047426, 0.15793045],
       [0.36308983, 0.        , 0.4169125 , 0.37780492, 0.74851708,
        0.59089448, 0.04316232, 0.15226253, 0.11261557, 0.52102028],
       [0.05382267, 0.4169125 , 0.        , 0.03910758, 0.33160458,
        0.17398198, 0.46007482, 0.56917503, 0.30429693, 0.10410778],
       [0.01471509, 0.37780492, 0.03910758, 0.        , 0.37071216,
        0.21308956, 0.42096723, 0.53006745, 0.26518935, 0.14321536],
       [0.38542725, 0.74851708, 0.33160458, 0.37071216, 0.        ,
        0.1576226 , 0.79167939, 0.9007796 , 0.6359015 , 0.2274968 ],
       [0.22780465, 0.59089448, 0.17398198, 0.21308956, 0.1576226 ,
        0.        , 0.63405679, 0.743157  , 0.4782789 , 0.0698742 ],
       [0.40625215, 0.04316232, 0.46007482, 0.42096723, 0.79167939,
        0.63405679, 0.        , 0.10910021, 0.15577789, 0.56418259],
       [0.51535236, 0.15226253, 0.5691750

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [ ]:
x = np.arange(11, dtype = np.float32)
x.astype(np.int32, copy = False)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int32)

#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [ ]:
from io import StringIO
s = StringIO("""1, 2, 3, 4, 5
              6,  ,  , 7, 8
            ,  , 9,10,11""")

x = np.genfromtxt(s, delimiter = ",", dtype = "i1")
x

array([[ 1,  2,  3,  4,  5],
       [ 6, -1, -1,  7,  8],
       [-1, -1,  9, 10, 11]], dtype=int8)

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [ ]:
x = np.arange(9).reshape(3, 3)
for index, value in np.ndenumerate(x):
  print(index, value)

print("*********************************")

for index in np.ndindex(x.shape):
  print(index, x[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
*********************************
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [ ]:
x, y = np.meshgrid(np.linspace(-1, 1, 10), np.linspace(-1, 1, 10))

a = np.sqrt(x*x + y*y)
sigma, mu = 1, 0
b = np.exp(-((a- 0)**2/(2*sigma**2)))
b

array([[0.36787944, 0.44822088, 0.51979489, 0.57375342, 0.60279818,
        0.60279818, 0.57375342, 0.51979489, 0.44822088, 0.36787944],
       [0.44822088, 0.54610814, 0.63331324, 0.69905581, 0.73444367,
        0.73444367, 0.69905581, 0.63331324, 0.54610814, 0.44822088],
       [0.51979489, 0.63331324, 0.73444367, 0.81068432, 0.85172308,
        0.85172308, 0.81068432, 0.73444367, 0.63331324, 0.51979489],
       [0.57375342, 0.69905581, 0.81068432, 0.89483932, 0.9401382 ,
        0.9401382 , 0.89483932, 0.81068432, 0.69905581, 0.57375342],
       [0.60279818, 0.73444367, 0.85172308, 0.9401382 , 0.98773022,
        0.98773022, 0.9401382 , 0.85172308, 0.73444367, 0.60279818],
       [0.60279818, 0.73444367, 0.85172308, 0.9401382 , 0.98773022,
        0.98773022, 0.9401382 , 0.85172308, 0.73444367, 0.60279818],
       [0.57375342, 0.69905581, 0.81068432, 0.89483932, 0.9401382 ,
        0.9401382 , 0.89483932, 0.81068432, 0.69905581, 0.57375342],
       [0.51979489, 0.63331324, 0.7344436

#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [ ]:
n = 10
x = np.zeros((n, n))
print(x)
p = 10
np.put(x, np.random.choice(range(n*n), p, replace=False),1)
print(x)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 1. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [ ]:
x = np.random.rand(3, 3)
print(x)
y = x - x.mean(axis = 1, keepdims= True)
y

[[0.76490457 0.2864219  0.17223402]
 [0.88764579 0.35352884 0.75922044]
 [0.22483815 0.05692609 0.20401959]]


array([[ 0.35705107, -0.1214316 , -0.23561948],
       [ 0.22084743, -0.31326952,  0.09242208],
       [ 0.06291021, -0.10500186,  0.04209165]])

#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [ ]:
x = np.random.randint(1, 50, 20).reshape(5, 4)
print(x)
print("*********************************")
print(x[x[:, 3].argsort()])

[[26 38 47  9]
 [36 25 23 25]
 [39 24 40 24]
 [14 38 27 39]
 [ 4  8 44 36]]
*********************************
[[26 38 47  9]
 [39 24 40 24]
 [36 25 23 25]
 [ 4  8 44 36]
 [14 38 27 39]]


#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [ ]:
x = np.random.randint(1, 20, (3, 3))
print(x)
print((~x.any(axis = 1)).any())

[[13  2 11]
 [ 8  3  4]
 [12  7  8]]
False


#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [ ]:
x = np.random.uniform(0, 1, 10)
print(x)
y = 0.3
z = x.flat[np.abs(x-y).argmin()]
z

[0.39382911 0.41289134 0.40206163 0.73569597 0.88301506 0.55892838
 0.11454849 0.98126248 0.82719019 0.91107144]


0.3938291073760801

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [ ]:
x = np.arange(3).reshape(3,1)
print(x)
y = np.arange(3).reshape(1,3)
print(y)
z = np.nditer([x,y,None])
print(z)
for m, n, p in z: 
  p[...] = m + n
  print(z.operands[2])

[[0]
 [1]
 [2]]
[[0 1 2]]
[[ 0 10  9]
 [11  9 10]
 [13 16  7]]
[[ 0  1  9]
 [11  9 10]
 [13 16  7]]
[[ 0  1  2]
 [11  9 10]
 [13 16  7]]
[[ 0  1  2]
 [ 1  9 10]
 [13 16  7]]
[[ 0  1  2]
 [ 1  2 10]
 [13 16  7]]
[[ 0  1  2]
 [ 1  2  3]
 [13 16  7]]
[[ 0  1  2]
 [ 1  2  3]
 [ 2 16  7]]
[[0 1 2]
 [1 2 3]
 [2 3 7]]
[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

In [ ]:
class NamedArray(np.ndarray):

  def __new__(cls, array, name="no name"):
    obj = np.asarray(array).view(cls)
    obj.name = name
    return obj

  def __array_finalize__(self, obj):
    if obj is None:
      return
    self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "guvi")

print (Z.name)

guvi


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [ ]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [ ]:
x = np.arange(11, 21)
y = np.arange(1, 11)
z = np.bincount(y, x)
z

array([ 0., 11., 12., 13., 14., 15., 16., 17., 18., 19., 20.])

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

In [ ]:
w,h = 4, 4

I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)

F = I[...,0]*2*2 + I[...,1]*2 +I[...,2]

n = len(np.unique(F))

print(np.unique(I))

[0 1]


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [ ]:
x = np.arange(81).reshape(3, 3, 3, 3)
x.sum(axis = (-2, -1))

array([[ 36, 117, 198],
       [279, 360, 441],
       [522, 603, 684]])

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [ ]:
x= np.random.uniform(0,1,100)
print(x)
y = np.random.randint(0,10,100)
print(y)
x_sums = np.bincount(y, weights=x)

x_counts = np.bincount(y)

x_means = x_sums / x_counts

print(x_means)


[0.75030375 0.61523077 0.89912279 0.72343465 0.29288768 0.372198
 0.42829331 0.78338142 0.37025033 0.07337079 0.41461581 0.59222612
 0.73024081 0.31500447 0.85536481 0.32063152 0.45933473 0.42993483
 0.72793778 0.02028357 0.50839057 0.344396   0.72196693 0.54231357
 0.88953495 0.83415653 0.86942108 0.79538781 0.57786042 0.03556211
 0.14629466 0.05470676 0.81423201 0.97022754 0.64515234 0.52013992
 0.63290356 0.59162547 0.39012331 0.26157916 0.84364061 0.81558135
 0.34655034 0.23636841 0.79117224 0.07155093 0.67585852 0.52318674
 0.8192802  0.43992182 0.51169416 0.89324629 0.53268593 0.84285892
 0.5685757  0.28732779 0.20899202 0.05101277 0.36377913 0.08274924
 0.38708303 0.4465939  0.55229218 0.93167461 0.89150493 0.99010631
 0.69465647 0.90130465 0.39327316 0.23653236 0.26093083 0.07635718
 0.60172911 0.46152914 0.66288659 0.36576007 0.17404724 0.76814382
 0.67547481 0.15598717 0.11372439 0.98568798 0.19598438 0.00291952
 0.29742058 0.62382032 0.87077604 0.71404039 0.93345813 0.536420

#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [ ]:
x = np.random.uniform(0, 100, 36).reshape(6, 6)
y = np.random.uniform(0, 100, 36).reshape(6, 6)
z = np.diag(np.dot(x, y))
print(x)
print(y)
z

[[ 8.07575317 61.89695157 76.41354692 51.02728554 68.81039483 69.79237997]
 [73.19053756 28.52131107 87.73118653 94.76486262 12.46115793 52.01257537]
 [79.95126231 52.30553874 68.13575021 24.56542914 32.86570012 83.53817951]
 [ 2.74256697 93.16087948 40.98278567 11.56158275 46.32863568  7.70258463]
 [24.9419865  35.72110578 12.59690458 16.90016455 35.34589989 15.49345568]
 [24.18608016 71.85676864 20.18882908 82.82298421  4.23729391 71.37562942]]
[[80.72286891 52.39531306 78.05220443 38.30157605 86.93462517 75.89505143]
 [40.7805238  86.44132535 77.58705372 63.97603072 22.54662333 81.06069801]
 [90.82161184 49.25605325 94.00617681 57.55101353 16.9665675  13.09338879]
 [26.75075164 66.61782097 46.14402263 98.99809818 72.29127241 62.68530665]
 [75.33307924 82.01569222 49.35245303 96.80423949 94.06244457 29.89706852]
 [86.98325722 29.15128701 83.31128759 84.56430791 11.93910133 40.26378588]]


array([22735.57527596, 19472.82571222, 26419.01023385, 14704.4555625 ,
        7918.87288185, 16117.02369775])

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [ ]:
x = np.arange(1, 6)
print(x)
y = np.zeros(len(x) + (len(x)-1)*3)
print(y)
y[::3+1] = x
print(y)

[1 2 3 4 5]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [ ]:
x = np.arange(75).reshape(5, 5, 3)
y = np.arange(25).reshape(5, 5)
print(x*y[:, :, None])

[[[   0    0    0]
  [   3    4    5]
  [  12   14   16]
  [  27   30   33]
  [  48   52   56]]

 [[  75   80   85]
  [ 108  114  120]
  [ 147  154  161]
  [ 192  200  208]
  [ 243  252  261]]

 [[ 300  310  320]
  [ 363  374  385]
  [ 432  444  456]
  [ 507  520  533]
  [ 588  602  616]]

 [[ 675  690  705]
  [ 768  784  800]
  [ 867  884  901]
  [ 972  990 1008]
  [1083 1102 1121]]

 [[1200 1220 1240]
  [1323 1344 1365]
  [1452 1474 1496]
  [1587 1610 1633]
  [1728 1752 1776]]]


#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [ ]:
x = np.arange(25).reshape(5, 5)
print(x)
print("************************************")
x[[0, 1]] = x[[1, 0]]
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

In [ ]:
faces = np.random.randint(0,100,(10,3))
print(faces)

F = np.roll(faces.repeat(2,axis=1),-1,axis=1)

F = F.reshape(len(F)*3,2)

F = np.sort(F,axis=1)

G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )

G = np.unique(G)

print(G)



[[86 47  4]
 [69 51 31]
 [31 80 25]
 [74 33 47]
 [26 80 96]
 [23 47 92]
 [55 33 74]
 [ 4 55 94]
 [ 1 14 45]
 [15 48 43]]
[( 1, 14) ( 1, 45) ( 4, 47) ( 4, 55) ( 4, 86) ( 4, 94) (14, 45) (15, 43)
 (15, 48) (23, 47) (23, 92) (25, 31) (25, 80) (26, 80) (26, 96) (31, 51)
 (31, 69) (31, 80) (33, 47) (33, 55) (33, 74) (43, 48) (47, 74) (47, 86)
 (47, 92) (51, 69) (55, 74) (55, 94) (80, 96)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [ ]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [ ]:
def moving_average(a, n=3) :
  ret = np.cumsum(a, dtype=float)
  ret[n:] = ret[n:] - ret[:-n]
  return ret[n - 1:] / n

Z = np.arange(20)

print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

In [ ]:
from numpy.lib import stride_tricks

def rolling(a, window):
  shape = (a.size - window + 1, window)
  strides = (a.itemsize, a.itemsize)
  return stride_tricks.as_strided(a, shape=shape, strides=strides)

Z = rolling(np.arange(10), 3)

print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [ ]:
Z = np.random.randint(0,2,100)
print(Z)
np.logical_not(Z, out=Z)
print(Z)
Z = np.random.uniform(-1.0,1.0,100)
print(Z)

np.negative(Z, out=Z)

[1 0 0 1 1 0 0 1 0 1 1 0 1 1 0 0 1 0 0 1 0 0 0 0 1 0 1 0 0 0 0 1 0 0 0 1 0
 1 1 0 0 1 0 0 1 1 0 0 0 1 0 1 1 1 0 1 0 1 1 0 0 0 1 1 1 1 1 0 0 0 0 0 0 1
 1 1 1 1 1 1 0 0 0 1 1 1 1 1 1 1 0 0 1 1 1 0 1 0 1 1]
[0 1 1 0 0 1 1 0 1 0 0 1 0 0 1 1 0 1 1 0 1 1 1 1 0 1 0 1 1 1 1 0 1 1 1 0 1
 0 0 1 1 0 1 1 0 0 1 1 1 0 1 0 0 0 1 0 1 0 0 1 1 1 0 0 0 0 0 1 1 1 1 1 1 0
 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 1 1 0 0 0 1 0 1 0 0]
[ 0.65522031  0.01687269  0.41211272 -0.46889619 -0.46952616  0.13187244
 -0.63362309  0.76699556 -0.99286611  0.80954865 -0.5846117  -0.16131706
  0.25849969  0.23029617  0.71232779 -0.65239123 -0.82723142 -0.95541675
 -0.82430361 -0.18637024  0.95899865 -0.52121461  0.50847741  0.71682899
 -0.31442338 -0.96899341  0.68121903  0.14009567 -0.61370067 -0.34457701
 -0.03808993  0.18980824 -0.64563004 -0.28960825  0.71779182  0.71418364
 -0.81765395  0.59208486 -0.51471698 -0.61757525  0.86625279 -0.26367541
  0.99588208 -0.15099119 -0.60600818  0.36867938  0.53979872  0.42195321
  0.2927

array([-0.65522031, -0.01687269, -0.41211272,  0.46889619,  0.46952616,
       -0.13187244,  0.63362309, -0.76699556,  0.99286611, -0.80954865,
        0.5846117 ,  0.16131706, -0.25849969, -0.23029617, -0.71232779,
        0.65239123,  0.82723142,  0.95541675,  0.82430361,  0.18637024,
       -0.95899865,  0.52121461, -0.50847741, -0.71682899,  0.31442338,
        0.96899341, -0.68121903, -0.14009567,  0.61370067,  0.34457701,
        0.03808993, -0.18980824,  0.64563004,  0.28960825, -0.71779182,
       -0.71418364,  0.81765395, -0.59208486,  0.51471698,  0.61757525,
       -0.86625279,  0.26367541, -0.99588208,  0.15099119,  0.60600818,
       -0.36867938, -0.53979872, -0.42195321, -0.29277559,  0.83349489,
       -0.59572559, -0.03227731, -0.85682426, -0.07661448, -0.91650121,
        0.84330137,  0.72545227,  0.40742518,  0.56294446, -0.92260985,
       -0.56460651, -0.36501787, -0.22281375,  0.19354096,  0.28398801,
        0.51944295, -0.30559572,  0.90742345,  0.96383811, -0.04

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [ ]:
def distance(P0, P1, p):

  T = P1 - P0
  L = (T**2).sum(axis=1)
  U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
  U = U.reshape(len(U),1)
  D = P0 + U*T - p
  return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
print(P0)
P1 = np.random.uniform(-10,10,(10,2))
print(P1)
p = np.random.uniform(-10,10,( 1,2))
print(p)
print(distance(P0, P1, p))



#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [ ]:
def distance(P0, P1, p):

  T = P1 - P0
  L = (T**2).sum(axis=1)
  U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
  U = U.reshape(len(U),1)
  D = P0 + U*T - p
  return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10, 10, (10,2))

P1 = np.random.uniform(-10,10,(10,2))

p = np.random.uniform(-10, 10, (10,2))

print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[18.72675289 10.74264308  8.70472796  0.5489031  11.36479687  6.40429284
   3.29159511 14.53251464  3.44778565 12.29461994]
 [10.0911284   1.63490068  3.64250417  0.36803003 11.54643348  1.81319083
   5.85350016  5.68040038  3.73700212  3.51033504]
 [17.58472626 13.11626419  4.06416135  6.98960539  4.99241223  4.57279163
   3.50575857 13.84648127  8.41540494 11.45476997]
 [ 0.93510243  4.62597016  8.77892539  8.30607084  2.18186844 13.4229031
  15.39447307  4.89517437  4.03235631  7.22286098]
 [ 0.16715325  1.66859418 13.82854293 17.83493626  7.01568391 13.44224611
  12.18536733  3.07019053  5.37258729  5.64002006]
 [ 0.63054656  3.16746875  7.64722375  8.11883404  2.49349716 11.89294438
  13.81314063  3.31638106  3.04852288  5.64759627]
 [ 7.39674938  7.68724524  7.80791445 15.65692562  4.29641416  6.22838369
   5.16828659  4.1231008   8.73108964  1.56956033]
 [ 1.09665643  2.41361347 13.02251928 17.50210557  6.61459627 12.50877245
  11.29464285  2.14925491  5.75676539  4.71568018]
 

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

In [ ]:
Z = np.random.randint(0,10,(10,10))

shape = (5,5)

fill = 0

position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill

P = np.array(list(position)).astype(int)

Rs = np.array(list(R.shape)).astype(int)

Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)

R_stop = np.array(list(shape)).astype(int)

Z_start = (P-Rs//2)

Z_stop = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()

Z_start = (np.maximum(Z_start,0)).tolist()

R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()

Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]

z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]

R[r] = Z[z]

print(Z)

print(R)

[[5 6 9 1 7 5 5 5 9 4]
 [0 7 9 4 7 2 3 2 3 6]
 [9 9 8 7 6 3 0 5 0 8]
 [1 7 0 3 7 5 5 6 5 1]
 [8 8 9 5 0 7 6 0 6 4]
 [5 4 1 9 3 3 7 3 6 9]
 [2 6 5 7 1 3 2 3 2 0]
 [1 0 2 2 8 4 0 8 3 5]
 [4 8 0 2 3 8 3 5 0 0]
 [3 3 2 4 5 5 2 4 6 3]]
[[0 0 0 0 0]
 [0 5 6 9 1]
 [0 0 7 9 4]
 [0 9 9 8 7]
 [0 1 7 0 3]]


<ipython-input-200-0a16cdf0f6a6>:37: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  R[r] = Z[z]


#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [ ]:
z = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14])
a = rolling(z, 4)
print(a)

#or 
print("***********************************")

x = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14],dtype=np.uint32)

R = stride_tricks.as_strided(x,(11, 4),(4,4))

print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]
***********************************
[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [ ]:
x = np.random.uniform(0,1,(1, 5, 10))
U, S, V = np.linalg.svd(x)
rank = np.sum(S > 1e-10)
#print(x)
print(rank)
print(S)

5
[[3.90383766 1.15660351 0.89049921 0.66915951 0.47214909]]


#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [ ]:
x = np.random.randint(1, 100, 30)
print(np.bincount(x).argmax())

24


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [ ]:
x = np.random.randint(1, 100,(10, 10))
n = 3
i = 1 + (x.shape[0]-3)
j = 1 + (x.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=x.strides + x.strides)

print(C)

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

In [ ]:
class Symetric(np.ndarray):
  def __setitem__(self, index, value):
    i,j = index
    super(Symetric, self).__setitem__((i,j), value)
    super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
  return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))

S[2,3] = 42

print(S)

[[ 1  9  3  8 15]
 [ 9  8  6  5  8]
 [ 3  6  4 42  7]
 [ 8  5 42  1  5]
 [15  8  7  5  9]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

In [ ]:
p, n = 10, 20

M = np.ones((p,n,n))

V = np.ones((p,n,1))

S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])

print(S)



[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

In [ ]:
x = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(x, np.arange(0, x.shape[0], k), axis=0),
np.arange(0, x.shape[1], k), axis=1)

print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [ ]:
def iterate(Z):
  N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
  Z[1:-1,0:-2] + Z[1:-1,2:] +
  Z[2: ,0:-2] + Z[2: ,1:-1] + Z[2: ,2:])

# Apply rules

  birth = (N==3) & (Z[1:-1,1:-1]==0)

  survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)

  Z[...] = 0

  Z[1:-1,1:-1][birth | survive] = 1

  return Z

Z = np.random.randint(0,2,(50,50))

for i in range(100):
  Z = iterate(Z)
print(Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [ ]:
Z = np.arange(10000)

np.random.shuffle(Z)

y = np.arange(1, 11)
for n in y:
  print (Z[np.argsort(Z)[-n:]])

[9999]
[9998 9999]
[9997 9998 9999]
[9996 9997 9998 9999]
[9995 9996 9997 9998 9999]
[9994 9995 9996 9997 9998 9999]
[9993 9994 9995 9996 9997 9998 9999]
[9992 9993 9994 9995 9996 9997 9998 9999]
[9991 9992 9993 9994 9995 9996 9997 9998 9999]
[9990 9991 9992 9993 9994 9995 9996 9997 9998 9999]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

In [ ]:
def cartesian(arrays):
  arrays = [np.asarray(a) for a in arrays]
  shape = (len(x) for x in arrays)
  ix = np.indices(shape, dtype=int)
  ix = ix.reshape(len(arrays), -1).T
  for n, arr in enumerate(arrays):
    ix[:, n] = arrays[n][ix[:, n]]
    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 0 0]
 [1 0 1]
 [1 1 0]
 [1 1 1]
 [2 0 0]
 [2 0 1]
 [2 1 0]
 [2 1 1]
 [3 0 0]
 [3 0 1]
 [3 1 0]
 [3 1 1]]


#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

In [ ]:
Z = np.array([("Tamizh", 18.5, 23),("arasan", 13.6, 24)])

R = np.core.records.fromarrays(Z.T,names='col1, col2, col3',formats = 'a8, f4, i2')

print(R)

[(b'Tamizh', 18.5, 23) (b'arasan', 13.6, 24)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

In [ ]:
x = np.random.randint(5e7)
#x.astype(int)
%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

1.91 µs ± 643 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
149 ns ± 2 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

In [ ]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = (C.sum(axis=(1,2,3)) >= B.shape[1]).nonzero()[0]
print(rows)

[1 2 4 7]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [ ]:
Z = np.random.randint(0,30,(10,3))
E = np.logical_and.reduce(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(Z)
print("*****************************************")
print(U)

[[18 10 24]
 [ 7  8 16]
 [ 2 27 22]
 [ 2 29 25]
 [ 6 20 10]
 [28  2 25]
 [13 28 13]
 [16 18 25]
 [26 26  7]
 [12 20 24]]
*****************************************
[[18 10 24]
 [ 7  8 16]
 [ 2 27 22]
 [ 2 29 25]
 [ 6 20 10]
 [28  2 25]
 [13 28 13]
 [16 18 25]
 [26 26  7]
 [12 20 24]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

In [ ]:
x = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)

print(np.unpackbits(x[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

In [ ]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]

print(uZ)

[[0 0 0]
 [0 1 0]
 [1 0 0]
 [1 1 1]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

In [ ]:
A= np.arange(3)
B =  np.arange(3)
print (A)
np.einsum('i->', A)       # np.sum(A)
np.einsum('i,j->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('...i,j', A, B)    # np.outer(A, B)

[0 1 2]


array([[0, 0, 0],
       [0, 1, 2],
       [0, 2, 4]])

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

In [ ]:
phi = np.arange(0, 10*np.pi, 0.1)

a = 1

x = a*phi*np.cos(phi)

y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths

r = np.zeros_like(x)

r[1:] = np.cumsum(dr) # integrate path

r_int = np.linspace(0, r.max(), 200) # regular spaced path

x_int = np.interp(r_int, r, x) # integrate path

y_int = np.interp(r_int, r, y)



#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

In [ ]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],

[2.0, 0.0, 1.0, 1.0],

[1.5, 2.5, 1.0, 0.0]])

n = 4

M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)

M &= (X.sum(axis=-1) == n)

print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)

In [ ]:
X = np.random.randn(100) # random 1D array

N = 1000 # number of bootstrap samples

idx = np.random.randint(0, X.size, (N, X.size))

means = X[idx].mean(axis=1)

confint = np.percentile(means, [2.5, 97.5])

print(confint)

[-0.23187269  0.14037387]
